workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 60
    environment:
      vars:
        APP_NAME: "ExplosivesCalculatorR"
      xcode: latest
    scripts:
      - name: Install dependencies
        script: brew install cocoapods
      - name: Build app
        script: xcodebuild -workspace $APP_NAME.xcodeproj -scheme $APP_NAME -sdk iphoneos -configuration Release clean build
    artifacts:
      - build/ios/Release-iphoneos/*.ipa
